project:
  type: website
  output-dir: docs

website:
  title: "GIS Workshop - 2024"
  search:
    location: sidebar
    type: textbox
  bread-crumbs: true
  navbar:
    logo: layer-group-solid.svg
    background: "#000"
    foreground: "#fff"
    right:
      - href: index.qmd
      - href: slides.qmd
      - text: Topics
        menu: 
          - href: gis-concepts.qmd
          - href: intro-to-arcgis-pro.qmd
          - href: scripting-in-arcgis-pro.qmd
          - href: spatial-data-in-R.qmd
      - href: resources.qmd
  sidebar:
    background: "#f0f2f4"
    style: "floating"
    #logo: "slides/logo.png"
    search: true
    contents: 
      - text: "This workshop is kindly hosted by the Wildlife and Fisheries Sciences Graduate Student Organization at the Univeristy of Missouri."
      - href: https://gisgeography.com/gis-dictionary-definition-glossary/
        text: GIS Term Dictionary
        icon: question-circle-fill
      - href: https://pro.arcgis.com/en/pro-app/3.1/help/main/welcome-to-the-arcgis-pro-app-help.htm
        text: ArcGIS Pro Help Reference
        icon: question-circle-fill
      - href: https://pro.arcgis.com/en/pro-app/3.1/arcpy/main/arcgis-pro-arcpy-reference.htm
        text: ArcPy Help Reference
        icon: question-circle-fill
  page-footer:
    left:   <p xmlns:cc="http://creativecommons.org/ns#" >This work is licensed under <a href="http://creativecommons.org/licenses/by-nc/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1"></a></p> 
    center: "Created with R and Quarto by [btjepkes](https://btjepkes.github.io)."
    right: "Site not affiliated with the University of Missouri."
    background: "#000"
    foreground: "#fff"
format:
  html:
    link-external-icon: false
    link-external-newwindow: true
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      gutter-width: 4.5%
      body-width: 900px
