---
title: "Getting Started"
subtitle: "Welcome to the WAFSGSO Spring 2024 GIS Workshop!"
listing: 
  id: listings-schedule
  contents:
    - gis-concepts.qmd
    - intro-to-arcgis-pro.qmd
    - scripting-in-arcgis-pro.qmd
    - spatial-data-in-R.qmd
  filter-ui: false
  sort-ui: false
  type: table
  fields: 
    - title
    - subtitle
---

## Workshop Description

This workshop, **GIS for Fisheries and Wildlife Sciences**, provides a general introduction to GIS workflows and programming in the natural sciences. Topics will cover common data types, spatial operations, data visualization, and other tools used across the breadth of wildlife and fisheries research. No prior GIS experience is assumed, but might be helpful when following the more advanced portions of this workshop. High-level coding languages (e.g., Python and R) will also be included.

## Workshop Objectives

-   To provide an overview of GIS concepts and data types.
-   To introduce ArcGIS Pro (interface, projects, resources).
-   To demonstrate common spatial operations and tools.
-   To work through an example of programmatic GIS (Python).
-   To explore a variety of other tools and integrations (e.g., R).

## Data Downloads

Start by downloading workshop files here: [Workshop Files (Zipped)]() -- need to add.

> **Data used for this workshop came from the following:** <br><br>
> Eklund, Daniel A.; Donner, Deahn M.; Beck, Albert J.; Rugg, David J. 2023. Beaver colonization events on managed streams in the Chequamegon-Nicolet National Forest, Wisconsin. Fort Collins, CO: Forest Service Research Data Archive. https://doi.org/10.2737/RDS-2023-0019

## Workshop Schedule

This workshop is set to take approximately 4 hours to complete and will cover a diverse range of GIS topics. The following schedule outlines the general sections for each topic covered.

::: {#listings-schedule}
:::